# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - develop

pool:
  name: Default
  demands:
    - agent.name -equals ABBAS-THINKPAD

variables:
  buildConfiguration: 'Release'
  nodeVersion: '20.x'
  dotnetVersion: '8.0.x'

stages:
- stage: Build
  displayName: 'Build & Publish ShoppingWebsite'
  jobs:
  - job: Build_Frontend
    displayName: 'Build ShoppingWebsite.client (Vite)'

    steps:
    - checkout: self
  
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'

    - script: |
        echo "Running npm ci"
        npm ci
      displayName: 'npm ci'
      workingDirectory: '$(Build.SourcesDirectory)/shoppingwebsite.client'

    - script: |
        echo "Running npm run build"
        npm run build
      displayName: 'npm run build'
      workingDirectory: '$(Build.SourcesDirectory)/shoppingwebsite.client'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/shoppingwebsite.client/dist'
        artifact: 'frontend-dist'
  - job: Build_Backend
    displayName: 'Build & Publish ShoppingWebsite (ASP.NET Core) & Database'
    dependsOn: Build_Frontend

    steps:
    - checkout: self
  
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: restore
        projects: '**/ShippingWebsite.Server/*.csproj'

    - task: VSBuild@1
      displayName: Build solution
      inputs:
        solution: '**/ShoppingWebsite.sln'
        msbuildArgs: '/p:Configuration=$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish ShoppingWebsite.Server'
      inputs:
        command: publish
        projects: 'ShoppingWebsite.Server/ShoppingWebsite.Server.csproj'
        arguments: >
          --configuration $(buildConfiguration)
          --output $(Build.ArtifactStagingDirectory)/server-publish

    - task: VSBuild@1
      displayName: 'Build ShoppingWebsiteDb (DACPAC)'
      inputs:
        solution: 'ShoppingWebsiteDb/ShoppingWebsiteDb.sqlproj'
        msBuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutDir=$(Build.ArtifactStagingDirectory)/db/'

    - task: PublishPipelineArtifact@1
      displayName: Publish Backend Artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/server-publish'
        artifact: 'server-publish'

    - task: PublishPipelineArtifact@1
      displayName: Publish DACPAC Artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/db'
        artifact: db-publish


                